# Generated by Django 2.1.7 on 2019-02-28 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0002_auto_20190228_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='salary',
        ),
    ]
