# Generated by Django 2.1.7 on 2019-02-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0004_employee_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(default='Enter your Name here...', max_length=50),
        ),
    ]
