# Generated by Django 2.1.7 on 2019-02-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0005_auto_20190228_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='sector',
            field=models.CharField(choices=[('A', 'HR'), ('B', 'Audit'), ('C', 'Customers'), ('D', 'Sales')], default='HR', max_length=100),
        ),
    ]
