# Generated by Django 2.1.7 on 2019-02-28 17:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0007_auto_20190228_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(default='Enter your Name here...', max_length=50),
        ),
    ]
