# Generated by Django 2.1.7 on 2019-02-28 17:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0008_auto_20190228_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
        ),
    ]
