# Generated by Django 2.1.7 on 2019-02-28 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0009_employee_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='salary',
        ),
    ]
