# Generated by Django 2.1.7 on 2019-03-01 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0010_remove_employee_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='your_salary',
            field=models.CharField(default='0', editable=False, max_length=20),
        ),
    ]
