# Generated by Django 2.1.7 on 2019-03-01 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0012_auto_20190301_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='your_salary',
        ),
    ]
