# Generated by Django 2.1.7 on 2019-03-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0013_remove_employee_your_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.FloatField(default='0', editable=False, max_length=50),
        ),
    ]
