# Generated by Django 2.1.7 on 2019-03-02 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0014_employee_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='salary',
        ),
    ]
