# Generated by Django 2.1.7 on 2019-03-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0015_remove_employee_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='sector',
            field=models.CharField(choices=[('HR', 'HR'), ('Audit', 'Audit'), ('Customers', 'Customers'), ('Sales', 'Sales')], default='HR', max_length=100),
        ),
    ]
