# Generated by Django 2.1.7 on 2019-03-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0016_auto_20190302_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.FloatField(default='0', editable=False, max_length=50),
        ),
    ]
