# Generated by Django 2.1.7 on 2019-03-03 16:48

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0020_employee_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.FloatField(verbose_name=django.db.models.expressions.ExpressionWrapper(django.db.models.expressions.CombinedExpression(django.db.models.expressions.F('hrs'), '*', django.db.models.expressions.F('rate')), output_field=models.FloatField())),
        ),
    ]
