# Generated by Django 2.1.7 on 2019-03-05 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0023_auto_20190303_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='salary',
        ),
    ]
