# Generated by Django 2.1.7 on 2019-03-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0024_remove_employee_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='hrs',
            field=models.PositiveIntegerField(max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='rate',
            field=models.PositiveIntegerField(max_length=20),
        ),
    ]
