# Generated by Django 2.1.7 on 2019-03-05 10:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0026_auto_20190305_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hrs', models.PositiveIntegerField()),
                ('rate', models.PositiveIntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='hrs',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='rate',
        ),
    ]
