# Generated by Django 2.1.7 on 2019-03-05 10:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0028_salary_salary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Salary',
        ),
        migrations.AddField(
            model_name='employee',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='employee',
            name='hrs',
            field=models.PositiveIntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='employee',
            name='rate',
            field=models.PositiveIntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.PositiveIntegerField(default='0', editable=False),
        ),
    ]
