# Generated by Django 2.1.7 on 2019-03-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0031_auto_20190306_1350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Employee Salary', 'verbose_name_plural': 'Employee Salary'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.PositiveIntegerField(blank=True, default='0', null=True),
        ),
    ]
