# Generated by Django 2.1.7 on 2019-03-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0033_employee_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.PositiveIntegerField(blank=True, default='0', editable=False, null=True),
        ),
    ]
