# Generated by Django 2.1.7 on 2019-03-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0034_auto_20190306_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.PositiveIntegerField(blank=True, default='0', null=True),
        ),
    ]
