# Generated by Django 2.1.7 on 2019-03-06 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0036_auto_20190306_2018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Employees', 'verbose_name_plural': 'Employee'},
        ),
    ]
