# Generated by Django 2.1.7 on 2019-03-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0037_auto_20190306_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(default='Enter Employee Name here...', max_length=50),
        ),
    ]
