# Generated by Django 2.1.7 on 2019-03-16 11:25

from django.db import migrations, models
import salary.models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0038_auto_20190313_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='hrs',
            field=models.PositiveIntegerField(default='0', validators=[salary.models.Employee.hrs]),
        ),
    ]
