# Generated by Django 2.1.7 on 2019-03-16 14:16

from django.db import migrations, models
import salary.models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0049_auto_20190316_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='overtime',
        ),
        migrations.AlterField(
            model_name='employee',
            name='hrs',
            field=models.FloatField(default='0', validators=[salary.models.Employee.hrs]),
        ),
    ]
