# Generated by Django 2.1.7 on 2019-03-17 19:19

from django.db import migrations, models
import salary.models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0062_auto_20190317_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='hrs',
            field=models.FloatField(validators=[salary.models.Employee.hrs]),
        ),
    ]
